// ─── Types ─────────────────────────────────────────────────────────────────────

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  imageUrl: string;
  isAvailable: boolean;   // admin can toggle availability
  tags?: string[];        // e.g. ['veg', 'bestseller', 'spicy', 'special']
}

export interface CartItem {
  item: MenuItem;
  quantity: number;
  notes?: string;
}

export type OrderStatus = 'pending' | 'preparing' | 'ready' | 'completed';

export interface Order {
  id: string;
  tableNumber: number;
  items: { itemId: string; quantity: number; notes?: string }[];
  timestamp: string;       // ISO — when placed
  completedAt?: string;    // ISO — when marked ready/completed (for analytics)
  status: OrderStatus;
  totalAmount: number;     // stored for analytics without re-computing
  weatherMode?: string;    // sunny | rainy | cold etc.
}

// ─── All Categories from Official Sudama Bhel Menu ─────────────────────────────
export const CATEGORIES = [
  'Bhel & Chaat',
  'Breakfast & Snacks',
  'South Indian',
  'Pizza',
  'Sandwich',
  'Burger',
  'Maggi & Fries',
  'Hot & Cold Drinks',
  'Meals',
] as const;

export type MenuCategory = (typeof CATEGORIES)[number];

// ─── Official Sudama Bhel & Snacks Menu Items (पुण्याचे सुप्रसिद्ध सुदामा भेळ) ─────

export const MENU_ITEMS: MenuItem[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. भेळ आणि चाट (Bhel & Chaat)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'bhel_1',
    name: 'Pani Puri (पाणी पुरी)',
    description: 'Crispy hollow puris served with chilled tangy mint-coriander water, sweet tamarind chutney & spiced potato filling.',
    price: 25,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/pani-puri.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bhel_2',
    name: 'Masala Puri (मसाला पुरी)',
    description: 'Crispy crushed puris smothered in steaming spiced ragda, finely chopped onions, tomatoes, coriander and chatpata masala.',
    price: 40,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/masala-puri.jpg',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'bhel_3',
    name: 'Shev Puri (शेव पुरी)',
    description: 'Flat crisp puris loaded with diced potatoes, onions, trio of chutneys, ample crunchy nylon sev and fresh coriander.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/sev-puri.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bhel_4',
    name: 'SPDP - Sev Potato Dahi Puri (एस.पी.डी.पी.)',
    description: 'Pune specialty! Crisp puffed puris filled with potatoes, sweetened chilled dahi, tangy date-tamarind chutney & generous sev.',
    price: 60,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/dahi-puri.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'bhel_5',
    name: 'Ragda Puri (रगडा पुरी)',
    description: 'Hot spiced white pea ragda poured over crisp puris, garnished with fresh onions, sweet chutney, spicy teekha pani and sev.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/ragda-puri.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bhel_6',
    name: 'Cheese Shev Puri (चीज शेव पुरी)',
    description: 'Classic Shev Puri enriched with an abundant mountain of freshly grated processed cheese.',
    price: 80,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/cheese-shev-puri.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'bhel_7',
    name: 'Oli Bhel (ओली भेळ)',
    description: 'Authentic Puneri wet bhel made with roasted puffed rice, farsan, chopped onions, tomatoes, boiled potato & house chutneys.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/oli-bhel.avif',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bhel_8',
    name: 'Suki Bhel (सुकी भेळ)',
    description: 'Light, crunchy dry bhel with crisp kurmura, roasted peanuts, chana dal, sev, coriander, dry garlic chutney & lemon juice.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/suki-bhel.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bhel_9',
    name: 'Matki Bhel (मटकी भेळ)',
    description: 'Healthy and wholesome bhel tossed with steamed sprouted moth beans (matki), spicy masala, crunchy farsan and sev.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/matki-bhel.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bhel_10',
    name: 'Sudama Special Dahi Bhel (सुदामा स्पेशल दही भेळ)',
    description: 'Our iconic house creation! Signature bhel mixture doused in thick sweet beaten curd, tangy chutneys, pomegranate & sev.',
    price: 60,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/dahi-puri.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'bhel_11',
    name: 'Cheese Bhel (चीज भेळ)',
    description: 'Delectable crunchy bhel crowned with a lavish layer of creamy grated cheese.',
    price: 80,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/cheese-shev-puri.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bhel_12',
    name: 'Ragda Pattice (रगडा पॅटीस)',
    description: 'Golden shallow-fried spiced mashed potato patties served immersed in piping hot ragda gravy, sweet & green chutneys and sev.',
    price: 50,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/ragda-pattice.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bhel_13',
    name: 'Special Matki Bhel (स्पे. मटकी भेळ)',
    description: 'Extra rich sprouted matki bhel loaded with dry fruits, special masala, extra farsan and fresh lime.',
    price: 65,
    category: 'Bhel & Chaat',
    imageUrl: '/images/menu/special-matki-bhel.avif',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. ब्रेकफास्ट ॲन्ड स्नॅक्स (Breakfast & Snacks)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'snk_1',
    name: 'Pohe (पोहे)',
    description: 'Traditional Maharashtrian flattened rice cooked with onions, mustard seeds, green chillies, curry leaves, peanuts & lemon.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/pohe.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_2',
    name: 'Pohe Sambar (पोहे सांबर)',
    description: 'Warm fluffy kanda pohe served with a side of hot aromatic South Indian vegetable sambar.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/pohe-sambar.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_3',
    name: 'Pohe Sample (पोहे सॅम्पल)',
    description: 'Puneri classic! Warm seasoned pohe served with a bowl of fiery sample/tarri rassa.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/pohe-sample.webp',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'snk_4',
    name: 'Upitt / Upma (उपीट)',
    description: 'Wholesome semolina (rava) roasted and cooked with ginger, green chillies, mustard seeds, curry leaves & ghee.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/upma.webp',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_5',
    name: 'Shira / Sheera (शिरा)',
    description: 'Sweet golden semolina halwa prepared in pure ghee with sugar, aromatic cardamom and roasted nuts.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/sheera.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_6',
    name: 'Vada Pav (वडापाव)',
    description: 'Maharashtra’s heartbeat! Hot spicy batata vada tucked in soft pav with spicy red garlic chutney and fried green chilli.',
    price: 20,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/vada-pav.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_7',
    name: 'Cheese Vada Pav (चीज वडापाव)',
    description: 'Crispy batata vada nestled in buttered pav with melting cheese slice, spicy garlic powder & green chutney.',
    price: 30,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/cheese-vada-pav.webp',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'snk_8',
    name: 'Bread Pattice (ब्रेड पॅटीस)',
    description: 'Bread triangle stuffed with zesty spiced mashed potatoes, coated in besan batter and fried till golden & crisp.',
    price: 15,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/bread-pattice.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_9',
    name: 'Kanda Bhaji (कांदा भजी)',
    description: 'Pune’s beloved crispy, crunchy onion fritters seasoned with carom seeds and green chillies. Best with hot chai!',
    price: 40,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/kanda-bhaji.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_10',
    name: 'Batata Bhaji (बटाटा भजी)',
    description: 'Thin potato rounds dipped in light gram flour batter and fried into fluffy, crispy golden pakodas.',
    price: 40,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/batata-bhaji.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_11',
    name: 'Misal Pav (मिसळ पाव)',
    description: 'Iconic spicy sprouted lentil curry cooked with authentic Pune spices, served with crunchy farsan, chopped onions, lemon & 2 pav.',
    price: 70,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/misal-pav.jpg',
    isAvailable: true,
    tags: ['bestseller', 'spicy', 'veg'],
  },
  {
    id: 'snk_12',
    name: 'Pav Bhaji (पावभाजी)',
    description: 'Mashed medley of fresh garden vegetables slow-simmered on iron tawa with aromatic spices & generous butter, served with 2 buttery pav.',
    price: 80,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/pav-bhaji.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_13',
    name: 'Cheese Pav Bhaji (चीज पावभाजी)',
    description: 'Our rich, aromatic buttery pav bhaji loaded with overflowing shredded cheddar and processed cheese.',
    price: 100,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/cheese-pav-bhaji.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'snk_14',
    name: 'Batata Vada Sambar (बटाटा वडा सांबर)',
    description: 'Two hot batata vadas served in a bowl of piping hot vegetable sambar with fresh coconut chutney.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/batata-vada-sambar.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_15',
    name: 'Batata Vada Sample (बटाटा वडा सॅम्पल)',
    description: 'Two spiced batata vadas paired with spicy Kolhapuri/Puneri style sample kat rassa.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/batata-vada-sample.jpg',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'snk_16',
    name: 'Idli Sambar (इडली सांबर)',
    description: 'Two soft, fluffy steamed rice-urad dal idlis served with fragrant vegetable sambar and authentic coconut chutney.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/idli-sambar.webp',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_17',
    name: 'Idli Chutney (इडली चटणी)',
    description: 'Two warm, soft steamed idlis served with fresh South Indian coconut chutney.',
    price: 40,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/idli-chutney.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_18',
    name: 'Medu Vada Sambar (मेदु वडा सांबर)',
    description: 'Two crispy golden-fried lentil donuts with a fluffy soft interior, served with hot sambar and fresh coconut chutney.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/medu-vada.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'snk_19',
    name: 'Mix Vada Sambar (मिक्स वडा सांबर)',
    description: 'The best of both worlds: 1 steamed soft idli and 1 crunchy medu vada served with hot sambar & chutney.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/medu-vada.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_20',
    name: 'Butter Pav (Pair) (बटर पाव जोडी)',
    description: 'Pair of fresh soft pav buns toasted on tawa with generous pure butter.',
    price: 20,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/butter-pav.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_21',
    name: 'Single Pav (सिंगल पाव)',
    description: 'Single soft freshly baked bakery pav.',
    price: 5,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/single-pav.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'snk_22',
    name: 'Sabudana Vada (साबुदाणा वडा)',
    description: 'Crispy deep-fried tapioca pearl & peanut patties served with chilled sweet curd and spicy green chutney.',
    price: 50,
    category: 'Breakfast & Snacks',
    imageUrl: '/images/menu/sabudana-vada.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. साऊथ इंडियन (South Indian)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'sth_1',
    name: 'Plain Dosa (प्लेन डोसा)',
    description: 'Classic paper-crisp golden fermented crepe cooked with butter, served with piping hot sambar & fresh coconut chutney.',
    price: 50,
    category: 'South Indian',
    imageUrl: '/images/menu/plain-dosa.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sth_2',
    name: 'Masala Dosa (मसाला डोसा)',
    description: 'Crispy golden dosa stuffed with aromatic mustard-tempered potato onion masala, served with sambar & chutney.',
    price: 70,
    category: 'South Indian',
    imageUrl: '/images/menu/masala-dosa.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'sth_3',
    name: 'Onion Uttapam (ऑनियन उत्तापा)',
    description: 'Thick, fluffy savory fermented rice pancake topped with sweet caramelized onions, chillies, curry leaves & butter.',
    price: 80,
    category: 'South Indian',
    imageUrl: '/images/menu/uttapam.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sth_4',
    name: 'Loni Sponge Dosa (लोणी स्पंज डोसा)',
    description: 'Davangere style melt-in-the-mouth soft and fluffy set dosas topped with fresh white loni (butter) and potato bhaji.',
    price: 95,
    category: 'South Indian',
    imageUrl: '/images/menu/dosa-plate.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'sth_5',
    name: 'Cut Dosa (कट डोसा)',
    description: 'Crisp dosa coated with spicy Mysore chutney and potato filling, rolled and cut into handy party-style bite rolls.',
    price: 85,
    category: 'South Indian',
    imageUrl: '/images/menu/cut-dosa.jpg',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'sth_6',
    name: 'Paper Dosa (पेपर डोसा)',
    description: 'Extra-large, super-thin paper-crisp roasted dosa with golden butter glaze.',
    price: 95,
    category: 'South Indian',
    imageUrl: '/images/menu/plain-dosa.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sth_7',
    name: 'Cheese Masala Dosa (चीज मसाला डोसा)',
    description: 'Crisp masala dosa layered with flavorful potato sabzi and melted cheddar & mozzarella cheese.',
    price: 85,
    category: 'South Indian',
    imageUrl: '/images/menu/cheese-masala-dosa.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'sth_8',
    name: 'Cheese Uttapam (चीज उत्तापा)',
    description: 'Thick soft pancake loaded with diced tomatoes, onions, capsicum and overflowing melted cheese.',
    price: 90,
    category: 'South Indian',
    imageUrl: '/images/menu/uttapam.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sth_9',
    name: 'Cheese Sponge Dosa (चीज स्पंज डोसा)',
    description: 'Pillowy soft sponge dosas layered with golden butter and smothered with gooey cheese.',
    price: 95,
    category: 'South Indian',
    imageUrl: '/images/menu/dosa-plate.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sth_10',
    name: 'Cheese Cut Dosa (चीज कट डोसा)',
    description: 'Mumbai street style cut dosa packed with spicy bhaji, sautéed veggies and melting cheddar cheese.',
    price: 110,
    category: 'South Indian',
    imageUrl: '/images/menu/cheese-cut-dosa.webp',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. पिझ्झा (Pizza)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'piz_1',
    name: 'Cheese Pizza (चीझ पिझ्झा)',
    description: 'Crispy baked hand-tossed base layered with rich Italian tomato-herb sauce and generous mozzarella cheese.',
    price: 180,
    category: 'Pizza',
    imageUrl: '/images/menu/cheese-pizza.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'piz_2',
    name: 'Veg Pizza (व्हेज पिझ्झा)',
    description: 'Classic pizza topped with crunchy bell peppers, red onions, ripe tomatoes, sweet corn & mozzarella cheese.',
    price: 160,
    category: 'Pizza',
    imageUrl: '/images/menu/veg-pizza.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'piz_3',
    name: 'Cheese Corn Pizza (चीझ कॉर्न पिझ्झा)',
    description: 'Sweet American golden corn kernels layered with mozzarella on rich herb tomato sauce.',
    price: 150,
    category: 'Pizza',
    imageUrl: '/images/menu/cheese-corn-pizza.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'piz_4',
    name: 'Cheese Paneer Pizza (चीझ पनीर पिझ्झा)',
    description: 'Fresh marinated malai paneer cubes, capsicum, onions, Italian herbs and molten cheese.',
    price: 150,
    category: 'Pizza',
    imageUrl: '/images/menu/cheese-paneer-pizza.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'piz_5',
    name: 'Sudama Special Pizza (सुदामा स्पेशल पिझ्झा)',
    description: 'Chef signature! Loaded with spiced paneer, black olives, sweet corn, capsicum, onions, secret spice drizzle & double cheese.',
    price: 170,
    category: 'Pizza',
    imageUrl: '/images/menu/sudama-special-pizza.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'piz_6',
    name: 'Cheese Garlic Bread (चीझ गार्लिक ब्रेड)',
    description: 'Freshly toasted baguette slices brushed with roasted garlic butter, oregano, parsley & gooey melted cheese.',
    price: 90,
    category: 'Pizza',
    imageUrl: '/images/menu/cheese-garlic-bread.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'piz_7',
    name: 'Cheese Chocolate Pizza (चीझ चॉकलेट पिझ्झा)',
    description: 'Decadent dessert pizza topped with chocolate hazelnut spread, dark chocolate shavings and sweet creamy cheese.',
    price: 150,
    category: 'Pizza',
    imageUrl: '/images/menu/cheese-chocolate-pizza.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. सँडविच (Sandwich)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'sw_1',
    name: 'Veg Sandwich (व्हेज सँडविच)',
    description: 'Cool fresh sliced cucumber, tomatoes, boiled potatoes and onions layered with butter and zesty coriander-mint chutney.',
    price: 60,
    category: 'Sandwich',
    imageUrl: '/images/menu/veg-sandwich.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sw_2',
    name: 'Veg Cheese Sandwich (व्हेज चीज सँडविच)',
    description: 'Fresh vegetable sandwich topped with sliced cheese, seasoned with chatpata sandwich masala.',
    price: 70,
    category: 'Sandwich',
    imageUrl: '/images/menu/veg-cheese-grilled-sandwich.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sw_3',
    name: 'Veg Grilled Sandwich (व्हेज ग्रील्ड सँडविच)',
    description: 'Crisp golden grilled sandwich packed with spiced potato filling, onions, bell peppers and mint chutney.',
    price: 80,
    category: 'Sandwich',
    imageUrl: '/images/menu/veg-grilled-sandwich.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'sw_4',
    name: 'Veg Cheese Grilled Sandwich (व्हेज चीज ग्रील्ड सँडविच)',
    description: 'Tawa-grilled crisp sandwich oozing with melted cheese, seasoned vegetables and spicy mint chutney.',
    price: 90,
    category: 'Sandwich',
    imageUrl: '/images/menu/veg-cheese-grilled-sandwich.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'sw_5',
    name: 'Veg Cheese Grilled Corn Sandwich (व्हेज चीज ग्रील्ड कॉर्न सँडविच)',
    description: 'Triple-layer grilled sandwich filled with sweet American corn, crunchy capsicum & loads of melted cheese.',
    price: 100,
    category: 'Sandwich',
    imageUrl: '/images/menu/veg-cheese-grilled-corn-sandwich.avif',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'sw_6',
    name: 'Chocolate Sandwich (चॉकलेट सँडविच)',
    description: 'Warm grilled sandwich oozing with rich chocolate fudge spread and chocolate chips.',
    price: 80,
    category: 'Sandwich',
    imageUrl: '/images/menu/chocolate-sandwich.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'sw_7',
    name: 'Cheese Chocolate Sandwich (चीज चॉकलेट सँडविच)',
    description: 'The ultimate indulgent treat: molten chocolate ganache balanced with creamy cheese between crisp grilled bread.',
    price: 100,
    category: 'Sandwich',
    imageUrl: '/images/menu/cheese-chocolate-pizza.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. बर्गर (Burger)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'bg_1',
    name: 'Veg Tikki Burger (व्हेज टिक्की बर्गर)',
    description: 'Golden spiced potato-pea tikki patty with crunchy lettuce, onions, tomatoes and herb mayonnaise in toasted sesame bun.',
    price: 60,
    category: 'Burger',
    imageUrl: '/images/menu/veg-tikki-burger.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bg_2',
    name: 'Veg Burger (व्हेज बर्गर)',
    description: 'Crisp vegetable patty with tangy cocktail sauce, fresh cucumber, tomatoes and shredded coleslaw.',
    price: 80,
    category: 'Burger',
    imageUrl: '/images/menu/veg-burger.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bg_3',
    name: 'Veg Cheese Burger (व्हेज चीज बर्गर)',
    description: 'Crisp vegetable burger crowned with melted cheddar cheese slice and creamy garlic mayo.',
    price: 90,
    category: 'Burger',
    imageUrl: '/images/menu/veg-cheese-burger.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'bg_4',
    name: 'Veg Shezwan Burger (व्हेज शेझवान बर्गर)',
    description: 'Spicy punch! Crisp veg patty tossed in fiery Schezwan chilli garlic sauce with crunchy capsicum and onions.',
    price: 90,
    category: 'Burger',
    imageUrl: '/images/menu/veg-shezwan-burger.jpg',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'bg_5',
    name: 'Veg Shezwan Cheese Burger (व्हेज शेझवान चीज बर्गर)',
    description: 'Fiery Schezwan sauce paired with a rich melted cheese slice, crisp patty and toasted buttery bun.',
    price: 100,
    category: 'Burger',
    imageUrl: '/images/menu/veg-cheese-shezwan-burger.jpg',
    isAvailable: true,
    tags: ['spicy', 'special', 'veg'],
  },
  {
    id: 'bg_6',
    name: 'Paneer Burger (पनीर बर्गर)',
    description: 'Crispy crumb-coated paneer steak seasoned with tandoori spices, mint mayonnaise, lettuce and sliced onions.',
    price: 90,
    category: 'Burger',
    imageUrl: '/images/menu/paneer-burger.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'bg_7',
    name: 'Paneer Cheese Burger (पनीर चीज बर्गर)',
    description: 'Spiced golden paneer patty accompanied by a melted cheese slice, creamy mayo and crunchy veggies.',
    price: 90,
    category: 'Burger',
    imageUrl: '/images/menu/paneer-shezwan-cheese-burger.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'bg_8',
    name: 'Paneer Shezwan Burger (पनीर शेझवान बर्गर)',
    description: 'Marinated paneer patty drizzled with spicy homemade Schezwan sauce, coleslaw and pickled jalapeños.',
    price: 80,
    category: 'Burger',
    imageUrl: '/images/menu/paneer-shezwan-burger.jpeg',
    isAvailable: true,
    tags: ['spicy', 'veg'],
  },
  {
    id: 'bg_9',
    name: 'Paneer Shezwan Cheese Burger (पनीर शेझवान चीज बर्गर)',
    description: 'The heavyweight champ: spiced paneer patty, Schezwan kick, melting cheese slice & toasted brioche bun.',
    price: 100,
    category: 'Burger',
    imageUrl: '/images/menu/paneer-shezwan-cheese-burger.jpg',
    isAvailable: true,
    tags: ['special', 'spicy', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 7. मॅगी & फ्राईज् (Maggi & Fries)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'mg_1',
    name: 'Plain Maggi (प्लेन मॅगी)',
    description: 'Classic all-time favourite 2-minute Maggi noodles cooked with the signature aromatic tastemaker broth.',
    price: 60,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/maggi.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'mg_2',
    name: 'Masala Maggi (मसाला मॅगी)',
    description: 'Desi style Maggi tossed with sautéed onions, tomatoes, green peas, capsicum, butter & extra garam masala.',
    price: 70,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/maggi.jpg',
    isAvailable: true,
    tags: ['bestseller', 'spicy', 'veg'],
  },
  {
    id: 'mg_3',
    name: 'Special Cheese Maggi (स्पे. चीज मॅगी)',
    description: 'Hot spicy masala Maggi showered with an irresistible snowfall of melting grated cheese.',
    price: 80,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/maggi.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'fr_1',
    name: 'Plain Fries (प्लेन फ्राईज्)',
    description: 'Crispy golden potato French fries tossed with sea salt, served with tangy tomato ketchup.',
    price: 70,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/french-fries.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'fr_2',
    name: 'Peri-Peri Masala Fries (पेरी-पेरी मसाला फ्राईज्)',
    description: 'Crispy golden fries tossed in fiery African bird’s eye peri-peri spice dust.',
    price: 90,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/peri-peri-masala-fries.jpg',
    isAvailable: true,
    tags: ['spicy', 'bestseller', 'veg'],
  },
  {
    id: 'fr_3',
    name: 'Cheese Peri-Peri Masala Fries (चीज पेरी-पेरी मसाला फ्राईज्)',
    description: 'Fiery Peri-Peri fries drenched in warm cheddar cheese sauce and garnished with chilli flakes.',
    price: 120,
    category: 'Maggi & Fries',
    imageUrl: '/images/menu/peri-peri-masala-cheese-fries.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8. हॉट ड्रिंक्स ॲन्ड कोल्ड्रिंक्स (Hot & Cold Drinks)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'drk_1',
    name: 'Tea (Cutting) (चहा - कटींग)',
    description: 'Authentic Pune style adrak-elaichi cutting chai brewed strong with full-cream milk and spices.',
    price: 7,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/tea-cutting.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'drk_2',
    name: 'Tea (Full) (चहा - फुल)',
    description: 'Full cup of steaming hot freshly brewed masala tea.',
    price: 10,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/tea-full.webp',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'drk_3',
    name: 'Special Tea (स्पे. चहा)',
    description: 'Rich creamy special tea infused with crushed cardamom, ginger, saffron & lemongrass.',
    price: 20,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/tea-full.webp',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'drk_4',
    name: 'Hot Coffee (हॉट कॉफी)',
    description: 'Freshly whipped frothy hot coffee prepared with rich roast beans and steamed milk.',
    price: 20,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/filter-coffee.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'drk_5',
    name: 'Black Tea (ब्लॅक टी)',
    description: 'Aromatic pure black tea steeped without milk, served with lemon slice.',
    price: 20,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/black-tea.webp',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'drk_6',
    name: 'Lemon Tea (लेमन टी)',
    description: 'Zesty refreshing hot tea infused with freshly squeezed lemon juice and a touch of sweetness.',
    price: 20,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/lemon-tea.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'drk_7',
    name: 'Cold Coffee (कोल्ड कॉफी)',
    description: 'Pune’s favourite blended cold coffee with milk, coffee decoction, sugar and chocolate sauce swirl.',
    price: 40,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/thick-cold-coffee.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'drk_8',
    name: 'Chocolate Milkshake (चॉकलेट मिल्क शेक)',
    description: 'Chilled creamy milkshake blended with chocolate syrup and cocoa powder.',
    price: 40,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/chocolate-milkshake.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'drk_9',
    name: 'Thick Cold Coffee (थिक कोल्ड कॉफी)',
    description: 'Super thick, rich cold coffee blended with vanilla ice cream and topped with cocoa powder.',
    price: 50,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/thick-cold-coffee.jpg',
    isAvailable: true,
    tags: ['special', 'bestseller', 'veg'],
  },
  {
    id: 'drk_10',
    name: 'Thick Chocolate Milkshake (थिक चॉकलेट मिल्क शेक)',
    description: 'Ultra-thick milkshake loaded with chocolate ice cream, chocolate syrup & chocolate shavings.',
    price: 50,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/thick-chocolate-milkshake.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'drk_11',
    name: 'Thick Cold Coffee with Crush (थिक कोल्ड कॉफी - विथ क्रश)',
    description: 'Thick cold coffee blended with ice cream and topped with crunchy chocolate cookie crush.',
    price: 60,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/thick-cold-coffee-crush.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'drk_12',
    name: 'Thick Chocolate Milkshake with Crush (थिक चॉकलेट मिल्क शेक - विथ क्रश)',
    description: 'Velvety thick chocolate shake topped with Oreo/wafer crush and rich chocolate fudge.',
    price: 60,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/thick-chocolate-milkshake-crush.jpg',
    isAvailable: true,
    tags: ['special', 'veg'],
  },
  {
    id: 'drk_13',
    name: 'Buttermilk - Taak (ताक)',
    description: 'Traditional spiced buttermilk churned with roasted cumin seeds, ginger, green chillies & fresh coriander leaves.',
    price: 25,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/buttermilk-taak.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
  {
    id: 'drk_14',
    name: 'Water Bottle (पाणी बॉटल)',
    description: 'Packaged chilled mineral drinking water.',
    price: 20,
    category: 'Hot & Cold Drinks',
    imageUrl: '/images/menu/water-bottle.jpg',
    isAvailable: true,
    tags: ['veg'],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 9. मिल्स / जेवण (Meals)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'meal_1',
    name: 'Rice Plate / Veg Thali (राईस प्लेट - Veg Thali)',
    description: 'Complete wholesome meal: 3 Soft Wheat Chapatis, 2 Vegetable Sabjis (Bhaji), Dal Rice, Crispy Papad & Fresh Salad.',
    price: 80,
    category: 'Meals',
    imageUrl: '/images/menu/veg-thali.jpg',
    isAvailable: true,
    tags: ['bestseller', 'special', 'veg'],
  },
  {
    id: 'meal_2',
    name: 'Chapati Bhaji (चपाती भाजी)',
    description: '3 hot fresh tawa chapatis served with flavorful seasonal vegetable bhaji and fresh onion-lemon salad.',
    price: 50,
    category: 'Meals',
    imageUrl: '/images/menu/chapati-bhaji.jpg',
    isAvailable: true,
    tags: ['veg'],
  },
  {
    id: 'meal_3',
    name: 'Puri Bhaji (पुरी भाजी)',
    description: '4 golden puffed deep-fried puris served with aromatic spiced dry potato sukha bhaji and salad.',
    price: 60,
    category: 'Meals',
    imageUrl: '/images/menu/puri-bhaji.jpg',
    isAvailable: true,
    tags: ['bestseller', 'veg'],
  },
];
